# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'
networks:
  mynetwork:

volumes:
  datafiles:

services:
  mysql:
      image: mysql:latest
      ports:
        - "3307:3306"
      volumes:
        - datafiles:/var/lib/mysql
        # - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: Root0++
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: pass@word1234
        MYSQL_DATABASE: fintrack
      networks:
      - mynetwork

  fintrack:
    image: fintrack
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    depends_on: 
      - mysql
    ports:
      - "5000:80"
      - "5001:443"
    restart: always
    environment:
      # - DBHOST=mysql
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork

